### PR TITLE
Union types maps

### PR DESCRIPTION
**Pull request by dottorblaster**
This PR introduces support to union types, either unions of object types or primitive types. It should work in our use case :-)))

### CODE REVIEW

**Comment by dottorblaster** [comment]
Sorry for the huge PR but really most of it is generated code.

**Comment by nelsonkopliku** [comment]
What do you think of adding a `.tool-versions` file in the elixir directory?

**Comment by dottorblaster** [comment]
@nelsonkopliku what about a `.tool-versions` in the root of the projects with the golang version too?

**Comment by nelsonkopliku** [comment]
> @nelsonkopliku what about a `.tool-versions` in the root of the projects with the golang version too?
>

Sure!

**Review by nelsonkopliku — APPROVED** [review]
Super LGTM. Great job! :rocket: 

If you wish to add the `.tool-versions` in another PR, that's also fine.

There is only one issue with gpg in commits :confused:

**Review by CDimonaco — APPROVED** [review]
LGTM

**Pull request merged**
